# Generated by Django 4.2.1 on 2023-05-24 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='data_reg',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
