# Generated by Django 4.2.1 on 2023-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0002_user1_data_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=40, verbose_name='username'),
        ),
    ]
